const config=window.APP_CONFIG||{};
const API="https://api.themoviedb.org/3",IMG="https://image.tmdb.org/t/p/",hasToken=Boolean(config.TMDB_ACCESS_TOKEN),hasKey=Boolean(config.TMDB_API_KEY);
const demo=[
 {id:1,title:"네온 시티",name:null,release_date:"2026-08-12",vote_average:8.7,overview:"기억을 거래하는 미래 도시에서 한 형사가 사라진 진실을 추적한다.",poster_path:"https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=500&auto=format&fit=crop",backdrop_path:"https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1600&auto=format&fit=crop"},
 {id:2,title:"심해의 노래",release_date:"2026-07-21",vote_average:8.2,overview:"미지의 신호를 따라 심해로 향한 탐사대의 경이로운 여정.",poster_path:"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=500&auto=format&fit=crop",backdrop_path:"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1600&auto=format&fit=crop"},
 {id:3,title:"마지막 궤도",release_date:"2026-06-10",vote_average:7.9,overview:"지구로 귀환할 단 한 번의 기회를 둘러싼 우주 생존 드라마.",poster_path:"https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=500&auto=format&fit=crop",backdrop_path:"https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=1600&auto=format&fit=crop"},
 {id:4,title:"붉은 정원",release_date:"2026-05-02",vote_average:8.4,overview:"평화로운 저택에 숨겨진 가족의 비밀이 하나씩 드러난다.",poster_path:"https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500&auto=format&fit=crop",backdrop_path:"https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop"},
 {id:5,title:"서울 2049",release_date:"2026-04-18",vote_average:8.1,overview:"인공지능과 인간이 공존하는 서울, 선택받은 배달원이 도시를 구한다.",poster_path:"https://images.unsplash.com/photo-1519608487953-e999c86e7455?w=500&auto=format&fit=crop",backdrop_path:"https://images.unsplash.com/photo-1519608487953-e999c86e7455?w=1600&auto=format&fit=crop"},
 {id:6,title:"여름의 조각",release_date:"2026-03-11",vote_average:7.8,overview:"오래된 사진 한 장이 두 사람의 여름을 다시 연결한다.",poster_path:"https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=500&auto=format&fit=crop",backdrop_path:"https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=1600&auto=format&fit=crop"}
];
let all=[],heroItems=[],heroIndex=0,heroRequestId=0;
const $=s=>document.querySelector(s), image=(p,size="w500")=>!p?"":p.startsWith("http")?p:`${IMG}${size}${p}`;
async function request(path,label=path){const sep=path.includes("?")?"&":"?",url=`${API}${path}${sep}language=ko-KR${hasKey?`&api_key=${config.TMDB_API_KEY}`:""}`;const headers=hasToken?{Authorization:`Bearer ${config.TMDB_ACCESS_TOKEN}`}:{ };const res=await fetch(url,{headers});if(!res.ok)throw new Error(`TMDB ${res.status}`);const data=await res.json();console.log(`[TMDB API] ${label}`,data);return data}
function card(item,i){const title=item.title||item.name||"제목 없음",date=item.release_date||item.first_air_date||"",poster=image(item.poster_path);return `<article class="card" data-id="${item.id}">${i<10?`<span class="rank">TOP ${i+1}</span>`:""}<img src="${poster}" alt="${title} 포스터" loading="lazy"><div class="card-info"><h3>${title}</h3><p>★ ${(item.vote_average||0).toFixed(1)} · ${date.slice(0,4)||"공개 예정"}</p></div></article>`}
function renderRow(id,items){$(id).innerHTML=items.map(card).join("");$(id).querySelectorAll(".card").forEach(el=>el.onclick=()=>openModal(items.find(x=>String(x.id)===el.dataset.id)))}
async function setHero(item){if(!item)return;const requestId=++heroRequestId,video=$("#heroVideo");video.classList.add("hidden");video.innerHTML="";$("#heroBg").style.backgroundImage=`url('${image(item.backdrop_path||item.poster_path,"original")}')`;$("#heroTitle").textContent=item.title||item.name;$("#heroMeta").textContent=`TOP 추천 · ${(item.release_date||item.first_air_date||"").slice(0,4)||"NEW"} · ★ ${(item.vote_average||0).toFixed(1)}`;$("#heroOverview").textContent=item.overview||"새로운 이야기를 만나보세요.";$("#heroInfo").onclick=()=>openModal(item);if(!(hasToken||hasKey))return;try{const type=item.media_type||(item.first_air_date?"tv":"movie"),data=await request(`/${type}/${item.id}/videos`,`${item.title||item.name} 영상 데이터`);if(requestId!==heroRequestId)return;const trailer=data.results.find(v=>v.site==="YouTube"&&v.type==="Trailer"&&v.official)||data.results.find(v=>v.site==="YouTube"&&(v.type==="Trailer"||v.type==="Teaser"));if(!trailer)return;video.innerHTML=`<iframe src="https://www.youtube.com/embed/${trailer.key}?autoplay=1&mute=1&controls=0&loop=1&playlist=${trailer.key}&playsinline=1&modestbranding=1&rel=0" title="${item.title||item.name} 미리보기 영상" allow="autoplay; encrypted-media"></iframe>`;video.classList.remove("hidden")}catch(error){console.warn("[TMDB API] 배너 영상 로드 실패",error)}}
function openModal(item){if(!item)return;$("#modalImage").style.backgroundImage=`url('${image(item.backdrop_path||item.poster_path,"original")}')`;$("#modalTitle").textContent=item.title||item.name;$("#modalMeta").textContent=`${(item.release_date||item.first_air_date||"").slice(0,4)||"공개 예정"} · ★ ${(item.vote_average||0).toFixed(1)}`;$("#modalOverview").textContent=item.overview||"상세 소개가 없습니다.";$("#modal").classList.remove("hidden");document.body.style.overflow="hidden"}
function closeModal(){$("#modal").classList.add("hidden");document.body.style.overflow=""}
async function load(){try{let popular,movies,tv;if(hasToken||hasKey){[popular,movies,tv]=await Promise.all([request("/trending/all/week","주간 인기 콘텐츠"),request("/movie/now_playing","현재 상영 영화"),request("/tv/popular","인기 TV 시리즈")]);popular=popular.results;movies=movies.results.map(x=>({...x,media_type:"movie"}));tv=tv.results.map(x=>({...x,media_type:"tv"}))}else throw new Error("no-key");all=[...popular,...movies,...tv].filter((v,i,a)=>a.findIndex(x=>x.id===v.id)===i);heroItems=popular.filter(x=>x.backdrop_path).slice(0,12);renderRow("#popularRow",popular);renderRow("#movieRow",movies);renderRow("#tvRow",tv)}catch(e){console.log("[CINEVERSE] 예시 콘텐츠 데이터",demo);all=[...demo];heroItems=demo;renderRow("#popularRow",demo);renderRow("#movieRow",[...demo].reverse());renderRow("#tvRow",[...demo.slice(2),...demo.slice(0,2)]);$("#notice").textContent="현재 예시 콘텐츠를 표시 중입니다. config.js에 TMDB API 키 또는 Read Access Token을 입력하면 실제 데이터로 자동 전환됩니다.";$("#notice").classList.remove("hidden")}heroIndex=Math.floor(Math.random()*heroItems.length);setHero(heroItems[heroIndex])}
$("#heroNext").onclick=()=>{heroIndex=(heroIndex+1)%heroItems.length;setHero(heroItems[heroIndex])};$("#modalClose").onclick=closeModal;$("#modal").onclick=e=>{if(e.target.id==="modal")closeModal()};document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});
document.querySelectorAll(".arrow").forEach(b=>b.onclick=()=>document.getElementById(b.dataset.target).scrollBy({left:(b.classList.contains("right")?1:-1)*window.innerWidth*.72,behavior:"smooth"}));
$("#searchForm").onsubmit=async e=>{e.preventDefault();const q=$("#searchInput").value.trim();if(!q)return;let results=all.filter(x=>(x.title||x.name||"").toLowerCase().includes(q.toLowerCase()));if((hasToken||hasKey)&&q.length>1){try{results=(await request(`/search/multi?query=${encodeURIComponent(q)}&include_adult=false`)).results.filter(x=>x.media_type!=="person")}catch{}}$("#contentRows").classList.add("hidden");$("#searchResults").classList.remove("hidden");$("#searchGrid").innerHTML=results.length?results.map(card).join(""):`<p>‘${q}’ 검색 결과가 없습니다.</p>`;$("#searchGrid").querySelectorAll(".card").forEach(el=>el.onclick=()=>openModal(results.find(x=>String(x.id)===el.dataset.id)))};
$("#closeSearch").onclick=()=>{$("#searchResults").classList.add("hidden");$("#contentRows").classList.remove("hidden");$("#searchInput").value=""};$("#menuBtn").onclick=()=>{const nav=$("#nav"),open=nav.classList.toggle("open");$("#menuBtn").setAttribute("aria-expanded",open)};$("#nav").onclick=()=>$("#nav").classList.remove("open");window.onscroll=()=>$("#header").classList.toggle("scrolled",scrollY>30);load();
